<?php
/**
 * This file is part of Integento_Catalog for Magento.
 *
 * @license MIT
 * @author Darklg <darklg.blog@gmail.com> <@Darklg>
 * @category Integento
 * @package Integento_Catalog
 * @copyright Copyright (c) 2016 Integento (http://github.com/InteGento)
 */

$_product = $this->getProduct();
$_imageSize = 135;
$_imgUrl = $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imageSize);

?>
<div class="product-item" itemscope itemtype="http://schema.org/Product">
    <meta itemprop="sku" content="<?php echo $_product->getSku() ?>" />
    <a itemprop="url" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
        <img itemprop="image" class="product-image" src="<?php echo $_imgUrl ?>" width="<?php echo $_imageSize; ?>" height="<?php echo $_imageSize; ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
        <h3 itemprop="name" class="product-name"><?php echo $this->escapeHtml($_product->getName()) ?></h3>
    </a>
    <div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer"><?php echo $this->getPriceHtml($_product, true, '-new') ?></div>
    <div class="actions">
        <?php if($_product->isSaleable()): ?>
        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button>
        <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></p>
        <?php endif; ?>
    </div>
</div>
